/**
 * Config de Tailwind de Mecánica Prime.
 * assets/styles.css fue generado a partir de esta config (extraída del script
 * inline que traía el archivo original) usando el motor JIT de Tailwind.
 * Si se agregan clases nuevas al HTML, hay que regenerar assets/styles.css.
 */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#5c403c",
        primary: "#b70011",
        "on-secondary-container": "#606369",
        "on-tertiary-fixed": "#0d1c2e",
        "surface-container-high": "#e2e7ff",
        "on-primary-fixed": "#410002",
        "surface-tint": "#bf0715",
        "outline-variant": "#e6bdb8",
        "surface-variant": "#dae2fd",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#93000b",
        tertiary: "#4c5b6f",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#44474d",
        "tertiary-fixed": "#d5e3fc",
        "inverse-primary": "#ffb4ab",
        surface: "#faf8ff",
        secondary: "#5c5e64",
        "surface-container": "#eaedff",
        "secondary-fixed-dim": "#c4c6cd",
        "inverse-surface": "#283044",
        "secondary-container": "#dedfe7",
        "surface-container-low": "#f2f3ff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#ffdad6",
        "on-surface": "#131b2e",
        "error-container": "#ffdad6",
        "secondary-fixed": "#e1e2e9",
        "tertiary-container": "#657388",
        "surface-bright": "#faf8ff",
        "tertiary-fixed-dim": "#b9c7df",
        "surface-dim": "#d2d9f4",
        "surface-container-lowest": "#ffffff",
        "on-background": "#131b2e",
        background: "#faf8ff",
        "primary-container": "#dc2626",
        "on-secondary-fixed": "#191c21",
        "on-primary-container": "#fff6f5",
        "primary-fixed-dim": "#ffb4ab",
        "on-tertiary-fixed-variant": "#3a485b",
        outline: "#916f6b",
        "on-tertiary-container": "#f7f8ff",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#dae2fd",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-sm": "0.75rem",
        "space-2xl": "3rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        "margin-desktop": "3rem",
        "container-max": "1280px",
        "space-4xl": "6rem",
        "space-xs": "0.5rem",
        "space-xl": "2rem",
        "space-md": "1rem",
        "margin-mobile": "1.25rem",
        "space-3xl": "4.5rem",
      },
      fontFamily: {
        "headline-sm": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-md": ["Space Grotesk"],
        "headline-xl-mobile": ["Space Grotesk"],
        "code-spec": ["Space Grotesk"],
        "display-mobile": ["Space Grotesk"],
        "headline-xl": ["Space Grotesk"],
        display: ["Space Grotesk"],
        "label-md": ["Space Grotesk"],
        "headline-lg-mobile": ["Space Grotesk"],
        "body-xl": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "label-sm": ["Space Grotesk"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-xl-mobile": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-spec": ["13px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "500" }],
        "display-mobile": ["38px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "52px", letterSpacing: "-0.025em", fontWeight: "600" }],
        display: ["64px", { lineHeight: "68px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-xl": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "700" }],
      },
    },
  },
};
